"""
Functions for cleaning autogenerated lables
"""
import gc

import numpy as np
from napari_cool_tools_io import torch, device, memory_stats
from napari.utils.notifications import show_info
from napari_cool_tools_vol_proc._masking_tools_funcs import project_2d_mask

#### TODO put memory and device handling functions in proper module

def get_accelerator_device() -> torch.device:
    """Detects available hardware using the PyTorch 2.9 Accelerator API."""
    if torch.accelerator.is_available():
        return torch.device(torch.accelerator.current_accelerator().type)
    return torch.device("cpu")

# TODO reimplement this once you upgrade pytorch to a newer version likely 2.9 or 3.0
# def reclaim_memory(device: torch.device) -> None:
#     """
#     Performs strict memory reclamation.
#     Triggers hardware cache clearing only for non-CPU devices.
#     """
#     # Force Python GC to destroy unreachable tensor references first
#     gc.collect()
    
#     # Clear hardware cache via the memory submodule in PyTorch 2.6+
#     if device.type != "cpu" and torch.accelerator.is_available():
#         torch.accelerator.memory.empty_cache()

# TODO replace this with above for now use this janky stuff
def reclaim_memory() -> None:
    """
    Performs strict memory reclamation.
    Uses device-specific calls as fallbacks for PyTorch 2.7.
    """
    # 1. Always run Python GC to destroy unreachable tensor references
    gc.collect()

    # In PyTorch 2.7, the unified memory submodule does not exist. 
    # We must route to the backend-specific clearing function.
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
    elif hasattr(torch, "mps") and torch.backends.mps.is_available():
        torch.mps.empty_cache()
    elif hasattr(torch, "xpu") and torch.backends.xpu.is_available():
        torch.xpu.empty_cache()
    # Add other 2.7-supported accelerators as needed (e.g., 'hpu')

####################################################################################

@torch.inference_mode()
def generate_elliptical_mask(data_shape,scale:float=1.0,symmetric_axis_offset:tuple=(0,0),center=None,major_axis=None,minor_axis=None,mask_depth=None,use_input_depth:bool=False,use_accelerator:bool=False,return_numpy:bool=True,verbose:bool=False):
    """"""
    if len(data_shape) != 3:
        raise ValueError(f"Functon requires a 3-dimensional data shape\n")

    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"

    # TODO modify to work with input center, major/minor axes
    #height,depth,width = data_shape
    major_axis,depth,minor_axis = data_shape
    major_axis = major_axis - 2*symmetric_axis_offset[0]
    minor_axis = minor_axis - 2*symmetric_axis_offset[1]
    major_axis = int(round(major_axis*scale))
    minor_axis = int(round(minor_axis*scale))
    center_major = major_axis // 2
    center_minor = minor_axis // 2 
    semi_major_axis = center_major
    sem_minor_axis = center_minor

    # calculate padding
    major_pad = (data_shape[0] - major_axis)//2
    minor_pad = (data_shape[2] - minor_axis)//2
    #radius = (min(height,width) / 2) * scale

    # Create a grid of coordinates
    major_at_coord, minor_at_coord = torch.meshgrid(torch.arange(-center_major,center_major,device=current_device),torch.arange(-center_minor,center_minor,device=current_device),indexing='ij')

    # Apply the ellipse equation: (x^2 / a^2) + (y^2 / b^2) <= 1
    # Pixels satisfying this condition are inside or on the border of the ellipse
    elliptical_mask = (major_at_coord**2 / semi_major_axis**2) + (minor_at_coord**2 / sem_minor_axis**2) <= 1
    

    if use_input_depth:
        mask_depth = depth

    # # Create a meshgrid of coordinates
    # height_at_coord,width_at_coord = torch.meshgrid(torch.arange(-height_center,height_center,device=current_device),torch.arange(-width_center,width_center,device=current_device),indexing='ij')
    # if verbose:
    #     print(f"height and width coordinate shapes: {height_at_coord.shape,width_at_coord.shape}\n")


    # distance_squared = height_at_coord**2 + width_at_coord**2
    # # compute circular mask
    # circular_mask = distance_squared <= radius**2

    if verbose:
        print("elliptical mask shape",elliptical_mask.shape, "mask_depth value", mask_depth)

    if mask_depth:
        elliptical_mask = elliptical_mask[:,None,:]
        elliptical_mask = elliptical_mask.expand(-1, mask_depth, -1)

    if major_pad > 0 or minor_pad > 0:
        elliptical_mask = torch.nn.functional.pad(elliptical_mask,(minor_pad,minor_pad,0,0,major_pad,major_pad))

    elliptical_mask = elliptical_mask.to(torch.bool).cpu()

    gc.collect()
    torch.cuda.empty_cache()
    if verbose:
        memory_stats()

    if not return_numpy:
        return elliptical_mask
    else:
        return elliptical_mask.numpy()
    
@torch.inference_mode()
def calculate_height_density_profile(
    voxel_grid: np.ndarray | torch.Tensor,
    window_height_voxels: int,
    use_tiling: bool = True,
    spatial_tile_size: tuple[int, int] = (420, 400),
    return_as_numpy: bool = False,
    use_bfloat16: bool = True,
    enable_visualization: bool = False,
    window_highlight_value: int = 10,
    center_slice_value: int = 6,
) -> (
    torch.Tensor
    | np.ndarray
    | tuple[torch.Tensor | np.ndarray, torch.Tensor | np.ndarray]
):
    """Calculates density profiles along axis 1 (Height) with CPU-bound output.

    Args:
        voxel_grid: 3D input grid of shape (Depth, Height, Width).
        window_height_voxels: Vertical sliding window size.
        use_tiling: If True, processes in spatial patches to save VRAM.
        spatial_tile_size: (Depth_Tile, Width_Tile) used if use_tiling is True.
        return_as_numpy: Returns results as NumPy arrays if True.
        use_bfloat16: Uses BF16 for math (recommended for RTX 3090+).
        enable_visualization: Returns a uint8 grid highlighting the max density region.
        window_highlight_value: uint8 value for the max density window.
        center_slice_value: uint8 value for the center slice of that window.

    Returns:
        A 1D density profile (CPU), or a tuple of (density profile, 3D visualization grid) (CPU).
    """
    F = torch.nn.functional
    input_tensor = torch.as_tensor(voxel_grid, dtype=torch.float32)
    target_device = input_tensor.device
    depth_full, height_full, width_full = input_tensor.shape
    computation_dtype = torch.bfloat16 if use_bfloat16 else torch.float16

    # Initialize global sum for 1D profile on target device
    global_profile_sum = torch.zeros(
        height_full, device=target_device, dtype=torch.float32
    )

    # if target_device.type != "cpu":
    reclaim_memory()
        #clean_hardware_resources()

    # 1. Processing Logic (Tiled vs. Full Volume)
    if not use_tiling:
        # Full volume calculation (Optimized for RTX 3090/24GB)
        working_tensor = input_tensor.permute(1, 0, 2)
        working_vol = working_tensor.unsqueeze(0).unsqueeze(0).to(computation_dtype)

        with torch.amp.autocast(
            device_type=target_device.type, dtype=computation_dtype
        ):
            vertical_kernel = torch.ones(
                (1, 1, window_height_voxels, 1, 1),
                device=target_device,
                dtype=computation_dtype,
            )
            density_sum_3d = F.conv3d(
                working_vol, vertical_kernel, padding=(window_height_voxels // 2, 0, 0)
            )

        density_sum_3d = density_sum_3d[:, :, :height_full, :, :].to(torch.float32)
        global_profile_sum = density_sum_3d.sum(dim=(0, 1, 3, 4))

        del working_tensor, working_vol, vertical_kernel, density_sum_3d
    else:
        # Tiled calculation (Optimized for 8GB VRAM cards)
        tile_depth_step, tile_width_step = spatial_tile_size
        for d_start in range(0, depth_full, tile_depth_step):
            d_end = min(d_start + tile_depth_step, depth_full)
            for w_start in range(0, width_full, tile_width_step):
                w_end = min(w_start + tile_width_step, width_full)

                tile_tensor = input_tensor[d_start:d_end, :, w_start:w_end]
                working_tile = tile_tensor.permute(1, 0, 2)
                current_h, current_td, current_tw = working_tile.shape
                working_vol = (
                    working_tile.unsqueeze(0).unsqueeze(0).to(computation_dtype)
                )

                with torch.amp.autocast(
                    device_type=target_device.type, dtype=computation_dtype
                ):
                    vertical_kernel = torch.ones(
                        (1, 1, window_height_voxels, 1, 1),
                        device=target_device,
                        dtype=computation_dtype,
                    )
                    tile_sum_3d = F.conv3d(
                        working_vol,
                        vertical_kernel,
                        padding=(window_height_voxels // 2, 0, 0),
                    )

                tile_sum_3d = tile_sum_3d[:, :, :current_h, :, :].to(torch.float32)
                global_profile_sum += tile_sum_3d.sum(dim=(0, 1, 3, 4))

                del tile_tensor, working_tile, working_vol, vertical_kernel, tile_sum_3d
                # if target_device.type != "cpu":
                reclaim_memory()
                    #clean_hardware_resources()

    # 2. Global Normalization
    normalization_factor = window_height_voxels * depth_full * width_full
    height_density_profile_gpu = global_profile_sum / (normalization_factor + 1e-9)

    # Move primary output to CPU
    height_density_profile = height_density_profile_gpu.cpu()
    del height_density_profile_gpu

    # 3. Optional Visualization Generation (Reconstructed on GPU then moved to CPU)
    visualization_grid = None
    if enable_visualization:
        # Calculate max density index (still on CPU-friendly scalar)
        max_idx = torch.argmax(height_density_profile).item()

        # Build 1D mask on device for fast expansion
        height_mask_1d = torch.zeros(
            height_full, dtype=torch.uint8, device=target_device
        )
        half_win = window_height_voxels // 2
        w_start, w_end = (
            max(0, max_idx - half_win),
            min(height_full, max_idx + half_win + 1),
        )

        height_mask_1d[w_start:w_end] = window_highlight_value
        height_mask_1d[max_idx] = center_slice_value

        # Expand and permute to (Depth, Height, Width)
        visualization_grid_gpu = height_mask_1d.view(1, height_full, 1).expand(
            depth_full, -1, width_full
        )

        # Move to CPU and release GPU handle
        visualization_grid = visualization_grid_gpu.cpu()

        del height_mask_1d, visualization_grid_gpu

    # 4. Final Cleanup of Large Tensors
    # if target_device.type != "cpu":
    del global_profile_sum
    # reclaim_memory()
        #clean_hardware_resources()

    # 5. Return Formatting
    output_profile = (
        height_density_profile.numpy() if return_as_numpy else height_density_profile
    )
    reclaim_memory()

    if enable_visualization:
        output_viz = (
            visualization_grid.numpy() if return_as_numpy else visualization_grid
        )
        reclaim_memory()
        return output_profile, output_viz

    return output_profile
    
def remove_lens_holder(data:np.ndarray|torch.Tensor,percentile:float=99.0,holder_height:int=64,pixel_offset:int=24,use_elliptical_mask:bool=True,return_mask:bool=False):
    """"""

    depth,_,width = data.shape
    width_depth_ratio = width/depth
    width_pixel_offset = round(width_depth_ratio*pixel_offset)

    preproc_data = np.zeros_like(data,dtype="uint8")
    preproc_data[data >= np.percentile(data, percentile)] = 1

    preproc_data_mask = generate_elliptical_mask(data.shape,use_input_depth=True)
    preproc_data[preproc_data_mask] = 0

    cleanup_mask = generate_elliptical_mask(data.shape,symmetric_axis_offset=(pixel_offset,width_pixel_offset),use_input_depth=True)
    # cleanup_mask = generate_elliptical_mask(data.shape,symmetric_axis_offset=(pixel_offset,pixel_offset),use_input_depth=True)

    _,density_label = calculate_height_density_profile(torch.as_tensor(preproc_data,device="cuda"),return_as_numpy=True,enable_visualization=True,window_height_voxels=holder_height,center_slice_value=6)
    # reclaim_memory()
    density_mask = density_label > 0
    # combo_mask = density_mask & ~preproc_data_mask

    if use_elliptical_mask:
        data[~preproc_data_mask] = 0
        lens_holder_mask = (preproc_data_mask & ~(cleanup_mask)) & density_mask
    else:
        lens_holder_mask = density_mask & ~cleanup_mask
    #lens_holder_mask = density_mask & ~cleanup_mask
    data[lens_holder_mask] = 0

    if not return_mask:
        return data
    else:
        return data,density_mask,lens_holder_mask

# TODO modify to use torch
def fill_ellipse(image_array:np.ndarray, center, major_axis_len, minor_axis_len, fill_value=1):
    """
    Fills pixels within the border of an ellipse in a NumPy array.

    Args:
        image_array (np.ndarray): The 2D NumPy array representing the image.
        center (tuple): A tuple (cy, cx) representing the center coordinates of the ellipse.
        major_axis_len (float): The length of the major axis.
        minor_axis_len (float): The length of the minor axis.
        fill_value (int or float): The value to fill the pixels with.
    """
    rows, cols = image_array.shape
    cy, cx = center
    
    # Calculate semi-major and semi-minor axes
    a = major_axis_len / 2
    b = minor_axis_len / 2

    # Create a grid of coordinates
    y_coords, x_coords = np.indices(image_array.shape)

    # Translate coordinates so the center is at (0,0)
    translated_x = x_coords - cx
    translated_y = y_coords - cy

    # Apply the ellipse equation: (x^2 / a^2) + (y^2 / b^2) <= 1
    # Pixels satisfying this condition are inside or on the border of the ellipse
    mask = (translated_y**2 / a**2) + (translated_x**2 / b**2) <= 1

    # Apply the mask to the image array
    image_array[mask] = fill_value

# TODO modify to use torch
def generate_elliptical_masks():
    # generate ellipse masks for clipping data beyond lens
    mask_840x800 = np.zeros((840,800),dtype=bool)
    mask_800x800 = np.zeros((800,800),dtype=bool)
    fill_ellipse(mask_840x800,center=(415,382.5),major_axis_len=(840/800)*700,minor_axis_len=700)
    fill_ellipse(mask_800x800,center=(405,395),major_axis_len=730,minor_axis_len=730)
    return (mask_840x800,mask_800x800)

def get_lens_mask_for_oct_volume(label_data_shape,mask_options:tuple[np.ndarray|torch.Tensor],verbose:bool=False):
    """
    """
    mask_0 = torch.as_tensor(mask_options[0])
    mask_1 = torch.as_tensor(mask_options[1])
    match tuple(torch.as_tensor(label_data_shape)[[0,2]]):
        case mask_0.shape:
            #lens_mask = torch.repeat_interleave(mask_0[:,None,:],label_data_shape[1],dim=1)
            lens_mask = mask_0.unsqueeze(1).expand(-1, label_data_shape[1], -1)
            if verbose:
                print(f"\nlens mask shape: {lens_mask.shape}")
                print(f"label data shape: {label_data_shape}")
            #label_data[~lens_mask] = 0
            return lens_mask.numpy()
        case mask_1.shape:
            lens_mask = mask_1.unsqueeze(1).expand(-1, label_data_shape[1], -1)
            if verbose:
                print(f"\nlens mask shape: {lens_mask.shape}")
                print(f"label data shape: {label_data_shape}")
            #label_data[~lens_mask] = 0
            return lens_mask.numpy()
        case _:
            message = f"Label data does not match any of the lens masks.\nGenerating Circular mask instead"
            print(message)
            lens_mask = generate_circular_mask(label_data_shape,use_input_depth=True)
            if verbose:
                print(f"\nlens mask shape: {lens_mask.shape}")
                print(f"label data shape: {label_data_shape}")  
            #label_data[~lens_mask] = 0
            return lens_mask.numpy()

def valid_coordinates(z_array:torch.Tensor):
    # make sure this is performed on the cpu
    z_array = z_array.cpu()
    # Find where z is not -1
    mask = z_array != -1

    # Get x and y coordinates
    y_indices, x_indices = torch.where(mask)

    # Get the corresponding z values
    z_values = z_array[y_indices, x_indices]

    # Stack into (N, 3) format: (x, y, z)
    coordinates = torch.column_stack((y_indices,z_values, x_indices))

    return coordinates

@torch.inference_mode()
def RPE_layer_coords(mask:np.ndarray|torch.Tensor,use_accelerator:bool=True,return_numpy:bool=False):

    # set device
    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"
    
    # convert to tensor if necessary
    if isinstance(mask,torch.Tensor):
        if mask.device.type != device.type:
            mask = mask.to(current_device)
    else:
        mask = torch.as_tensor(mask,device=current_device)

    mask = mask == 1
    mask = mask.to(torch.int16)
    mask = torch.where(mask.any(dim=1), mask.shape[1] -1 - torch.argmax(torch.flip(mask,dims=[1]), dim=1), -1)
    mask = mask.cpu()

    coords = valid_coordinates(mask)
    coords = coords.cpu()

    del mask
    gc.collect()
    if use_accelerator:
        torch.cuda.empty_cache()

    if not return_numpy:
        return coords
    else:
        return coords.numpy().astype("uint16")

@torch.inference_mode()    
def Retinal_surface_coords(mask:np.ndarray|torch.Tensor,use_accelerator:bool=True,return_numpy:bool=False):

    # set device
    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"
    
    # convert to tensor if necessary
    if isinstance(mask,torch.Tensor):
        if mask.device.type != device.type:
            mask = mask.to(current_device)
    else:
        mask = torch.as_tensor(mask,device=current_device)

    mask = mask == 1
    mask = mask.to(torch.int16)
    mask = torch.where(mask.any(dim=1), torch.argmax(mask, dim=1), -1)
    mask = mask.cpu()

    coords = valid_coordinates(mask)
    coords = coords.cpu()

    del mask
    gc.collect()
    if use_accelerator:
        torch.cuda.empty_cache()

    if not return_numpy:
        return coords
    else:
        return coords.numpy().astype("uint16")

@torch.inference_mode()    
def generate_thick_map(mask:np.ndarray|torch.Tensor,use_accelerator:bool=True,return_numpy:bool=True):
    """
    """
    # set device
    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"
    
    # convert to tensor if necessary
    if isinstance(mask,torch.Tensor):
        if mask.device.type != device.type:
            mask = mask.to(current_device)
    else:
        mask = torch.as_tensor(mask,device=current_device)

    slow_shape, axial_shape, fast_shape = mask.shape
    # get retinal and RPE surfaces
    rpe_coords = RPE_layer_coords(mask,use_accelerator=True,return_numpy=False).to(current_device)  # Shape: (N, 3)
    # rpe_coords = np.array(RPE_layer_coords(mask))  # Shape: (N, 3)

    retina_coords = Retinal_surface_coords(mask,use_accelerator=True,return_numpy=False).to(current_device)  # Shape: (M, 3)
    #retina_coords = np.array(Retinal_surface_coords(mask))  # Shape: (M, 3)

    del mask
    gc.collect()
    if use_accelerator:
        torch.cuda.empty_cache()

    retina_axial = retina_coords[:,1]
    rpe_axial = rpe_coords[:,1]
    thickness = ((rpe_axial+1) - retina_axial).to(torch.float32) # (rpe_axial+1) to account for zero index

    # # create thickness map
    thick_map = torch.zeros((slow_shape,fast_shape),dtype=torch.float32).to(current_device)
    #thick_map = np.zeros((slow_shape,fast_shape))
    thick_map[rpe_coords[:,0],rpe_coords[:,2]] = thickness

    thick_map = thick_map.cpu()
    retina_coords = retina_coords.cpu()
    rpe_coords = rpe_coords.cpu()

    del retina_axial,rpe_axial,thickness
    gc.collect()
    if use_accelerator:
        torch.cuda.empty_cache()
    if not return_numpy:
        return retina_coords,rpe_coords,thick_map
    if return_numpy:
        return retina_coords.numpy(),rpe_coords.numpy(),thick_map.numpy()

@torch.inference_mode()
def generate_depth_map(mask:np.ndarray|torch.Tensor,axis:int=1,normalized:bool=True,use_accelerator:bool=True,return_numpy:bool=True):
    """"""
    from napari_cool_tools_img_proc._normalization_funcs import normalize_data_in_range_pt_func

    # set device
    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"
    
    # convert to tensor if necessary
    if isinstance(mask,torch.Tensor):
        if mask.device.type != device.type:
            mask = mask.to(current_device)
    else:
        mask = torch.as_tensor(mask,device=current_device)

    depth = mask.shape[1]
    depth_map = mask.sum(dim=axis)

    del mask
    gc.collect()
    if use_accelerator:
        torch.cuda.empty_cache()

    if not normalized:
        depth_map = depth_map.cpu()
        if return_numpy:
            return depth_map.numpy()
        else:
            return depth_map
    else:
        depth_map = depth_map.to(torch.float32) / float(depth)
        depth_map = normalize_data_in_range_pt_func(depth_map,min_val=0.0,max_val=1.0,numpy_out=False,use_accelerator=use_accelerator)
        depth_map = depth_map.cpu()
        if not return_numpy:
            return depth_map
        else:
            return depth_map.numpy()

@torch.inference_mode()
def generate_circular_mask(data_shape,scale:float=1.0,mask_depth=None,use_input_depth:bool=False,use_accelerator:bool=False,return_numpy:bool=True,verbose:bool=False):
    """"""
    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"

    height,depth,width = data_shape
    height_center = height // 2
    width_center = width // 2 
    radius = (min(height,width) / 2) * scale

    if use_input_depth:
        mask_depth = depth

    # Create a meshgrid of coordinates
    height_at_coord,width_at_coord = torch.meshgrid(torch.arange(-height_center,height_center,device=current_device),torch.arange(-width_center,width_center,device=current_device),indexing='ij')
    if verbose:
        print(f"height and width coordinate shapes: {height_at_coord.shape,width_at_coord.shape}\n")


    distance_squared = height_at_coord**2 + width_at_coord**2
    # compute circular mask
    circular_mask = distance_squared <= radius**2

    if verbose:
        print("circular mask shape",circular_mask.shape, "mask_depth value", mask_depth)

    if mask_depth:
        circular_mask = circular_mask[:,None,:]
        #circular_mask = torch.repeat_interleave(circular_mask,mask_depth,dim=1)
        circular_mask = circular_mask.expand(-1, mask_depth, -1)


    circular_mask = circular_mask.cpu()
    del distance_squared
    gc.collect()
    torch.cuda.empty_cache()
    if verbose:
        memory_stats()

    if not return_numpy:
        return circular_mask
    else:
        return circular_mask.numpy()

@torch.inference_mode()
def generate_maps(label: np.ndarray|torch.Tensor,use_accelerator:bool=True,return_numpy:bool=True):
    """A custom function to produce depth, thickness, and difference maps from 3D label data."""

    # set device
    if use_accelerator:
        current_device = device
    else:
        current_device = "cpu"
    
    # convert to tensor if necessary
    if isinstance(label,torch.Tensor):
        if label.device.type != device.type:
            label = label.to(current_device)
    else:
        label = torch.as_tensor(label,device=current_device)

    # cylindrical_mask = generate_circular_mask(label.shape,scale=1.0,use_input_depth=True,use_accelerator=use_accelerator,return_numpy=False)
    # label[:] = label * cylindrical_mask
    raw_depth_map = generate_depth_map(label, normalized=False,use_accelerator=use_accelerator,return_numpy=return_numpy)
    retina_coords, rpe_coords, thick_map = generate_thick_map(label,use_accelerator=use_accelerator,return_numpy=return_numpy)
    difference_map = (thick_map - raw_depth_map)

    return (
        raw_depth_map,
        retina_coords,
        rpe_coords,
        thick_map,
        difference_map,
    )

def mask_3D_points_with_2D_boolean_mask(
    points_3D: np.ndarray,
    mask: np.ndarray,
    axis: int = 1,
    invert_mask: bool = False,
    verbose: bool = False,
) -> np.ndarray:
    """Filters a 3D array of points using a 2D boolean mask by projection.

    This function takes a 3D array of points and applies a 2D boolean mask to it.
    The mask is projected along the specified `axis` to generate a 3D boolean mask
    of the same shape as `points_3D`. This mask is then used to filter the
    `points_3D` array. Points where the mask is `True` are kept, while points
    where the mask is `False` are set to 0.

    Args:
        points_3D: A NumPy array of shape `(N, 3, ...)` or similar. The shape
        must conform to the specified checks, particularly that the second
        dimension must have a size of 3.
        mask: A 2D NumPy boolean array of shape `(H, W)`.
        axis: An integer specifying the dimension along which the 2D mask is
        broadcast to create the 3D mask.

    Returns:
        A NumPy array of the same shape as `points_3D` with the filtered points.
        If an error occurs, the original `points_3D` array is returned.

    Raises:
        ValueError: If the second dimension of `points_3D` is not 3.
        ValueError: If the `mask` is not a 2D array.
        ValueError: If the `mask` contains no `True` values.
        ValueError: If the total number of elements in the `mask` does not match
        the number of elements in the `points_3D` dimensions for the specified
        `axis`.
    """
    # --- Error checks ---
    if points_3D.shape[1] != 3:
        print(
            "Error: 'points_3D' must have a second dimension of size 3. "
            "Returning original array."
        )
        return points_3D

    if mask.ndim != 2:
        print("Error: 'mask' must be a 2D array. Returning original array.")
        return points_3D

    if not np.any(mask):
        print("Error: 'mask' contains no positive values. Returning original array.")
        return points_3D

    input_points = points_3D.copy().astype(int)

    # Build voxel grid from points data
    depth_min = int(input_points[:, 1].min())
    depth_max = int(input_points[:, 1].max())
    depth_shape = len(np.arange(depth_max - depth_min)) + 1  # adjust for 0 indexing

    if verbose:
        print(
            f"depth min: {depth_min}, depth max: {depth_max}, depth_shape: {depth_shape}\n"
        )

    voxel_grid = np.zeros((mask.shape[0], depth_shape, mask.shape[1])).astype(bool)
    if verbose:
        print(f"voxel grid shape: {voxel_grid.shape}\n")
    voxel_grid[
        input_points[:, 0], input_points[:, 1] - depth_min, input_points[:, 2]
    ] = 1  # offset depth points by min value to set it to zero

    # Expand mask to cover depth
    mask_3D = np.repeat(mask[:, None, :], depth_shape, axis=axis)
    if invert_mask:
        mask_3D = ~mask_3D
    voxel_grid = voxel_grid * mask_3D
    height, depth, width = voxel_grid.nonzero()
    masked_points_3D = np.column_stack((height, depth + depth_min, width))

    # return voxel_grid,masked_points_3D
    return masked_points_3D

#### TODO review and document ####
def generate_height_map_from_3D_points(
    points_3D: np.ndarray, shape: tuple, axis=1
) -> np.ndarray:
    """
    shape is the 2D shape of the output map
    """
    # def depth_from_points_3D(points_3D:np.ndarray,shape:tuple)->np.ndarray:
    # """
    # """
    depth_out = np.zeros(shape)
    # print(depth_out.shape)
    coordinates = np.arange(len(points_3D))
    # print(points_3D[coordinates,0],points_3D[coordinates,2],points_3D[coordinates,1])
    if axis == 1:
        depth_out[points_3D[coordinates, 0], points_3D[coordinates, 2]] = points_3D[
            coordinates, 1
        ]
    elif axis == 2:
        depth_out[points_3D[coordinates, 0], points_3D[coordinates, 1]] = points_3D[
            coordinates, 2
        ]
    elif axis == 0:
        depth_out[points_3D[coordinates, 1], points_3D[coordinates, 2]] = points_3D[
            coordinates, 0
        ]
    return depth_out

#### TODO review and document ####
def fill_nan_nearest_neighbor_2D(arr):
    """
    Fills NaN values in a 2D array using the nearest non-NaN neighbor.
    """
    filled_arr = np.copy(arr)
    rows, cols = filled_arr.shape

    # Create a mask for NaN values
    nan_mask = np.isnan(filled_arr)

    # Iterate until no more NaNs can be filled
    while np.any(nan_mask):
        new_nan_mask = np.copy(nan_mask)

        for r in range(rows):
            for c in range(cols):
                if nan_mask[r, c]:
                    # Check 8-directional neighbors
                    neighbors = []
                    for dr in [-1, 0, 1]:
                        for dc in [-1, 0, 1]:
                            if dr == 0 and dc == 0:
                                continue  # Skip self

                            nr, nc = r + dr, c + dc
                            if (
                                0 <= nr < rows
                                and 0 <= nc < cols
                                and not np.isnan(filled_arr[nr, nc])
                            ):
                                neighbors.append(filled_arr[nr, nc])

                    if neighbors:
                        # Replace NaN with the first found non-NaN neighbor (or mean/median)
                        filled_arr[r, c] = neighbors[0]
                        new_nan_mask[r, c] = False  # Mark as filled

        # Update the NaN mask for the next iteration
        if np.array_equal(nan_mask, new_nan_mask):  # No more NaNs filled in this pass
            break
        nan_mask = new_nan_mask

    return filled_arr

def outlier_correction(points_3D: np.ndarray, outlier_map: np.ndarray) -> np.ndarray:
    """ """
    in_points = points_3D.copy()
    outlier_mask = outlier_map > 0
    outlier_coords = np.column_stack(outlier_mask.nonzero())

    # remove outlier points
    # out_points = remove_outliers_by_xz_coords(out_points,outlier_xz_coords=outlier_coords)
    outlier_free_points = mask_3D_points_with_2D_boolean_mask(
        in_points, mask=outlier_map, axis=1, invert_mask=True
    )

    # Interpolate depth values
    height_map = generate_height_map_from_3D_points(
        points_3D=points_3D, shape=outlier_mask.shape, axis=1
    )
    # print(outlier_coords,outlier_coords.shape)
    height_outlier_nans = height_map.astype(float).copy()
    # height_outlier_nans[outlier_coords] = np.nan
    height_outlier_nans[outlier_mask] = np.nan
    interpolated_nans = fill_nan_nearest_neighbor_2D(height_outlier_nans)
    new_depth_vals = interpolated_nans[outlier_mask].flatten()
    #print(new_depth_vals.shape, outlier_coords.shape)

    # create points from depth values
    interpolated_points = np.column_stack(
        (outlier_coords[:, 0], new_depth_vals, outlier_coords[:, 1])
    )
    # interpolated_points = create_3d_points_from_depth(interpolated_nans,depth_axis_index=1)
    # return height_map,height_outlier_nans,interpolated_nans,create_3d_points_from_depth(interpolated_nans,depth_axis_index=1)
    # filtered_points = filter_points_with_2d_mask(interpolated_points,mask_2d=mask)
    # out_points[outlier_coords,1] = new_depth_vals
    out_points = np.concatenate((outlier_free_points, interpolated_points))
    return out_points, outlier_free_points, interpolated_nans

#### TODO review and document ####
def get_points_centroid_along_axis(
    points: np.ndarray, points2: np.ndarray, target_axes: list[int] = [1]
):
    """ """
    if points.size == 0 or points2.size == 0:
        print("One or both of the surface points arrays are empty. No centroid points will be produced.")
        return np.array([],dtype="uint8")
    elif len(points) != len(points2):
        print(f"The number of points between the two surfaces do not match {len(points) != {len(points2)}}. No centroid points will be produced.")
        return np.array([],dtype="uint8")
    
    axes = np.arange(len(points[0]))
    out_data = []
    for ax in axes:
        if ax in target_axes:
            out_data.append((points[:, ax] + points2[:, ax]) / 2)
        else:
            out_data.append(points[:, ax])
    return np.column_stack(out_data)

#### TODO review and document ####
def mask_components_within_theshold_of_points_distribution(
    binary_mask: np.ndarray,
    point_distirbution: np.ndarray,
    threshold: float,
    verbose: bool = False,
):
    """ """
    import cc3d
    from scipy.spatial import KDTree
    # ensure point distribution is of the proper dimenionality [num_points,dimensions/axes]

    # get connected components
    labeled_components = cc3d.connected_components(binary_mask, binary_image=True)
    # get statistics
    stats = cc3d.statistics(labeled_components)
    # get centroids
    centroids = stats["centroids"]
    # build kdtree for point_distribution
    point_distribution_kdtree = KDTree(point_distirbution)
    # find closest points for centroids
    distance_from_centroid, neighbor_index = point_distribution_kdtree.query(
        centroids, k=1, workers=-1
    )
    # filter centroids beyond the theshold distance
    indices_meet_criteria = (distance_from_centroid < threshold).nonzero()
    # build mask of components that meet the criteria
    if verbose:
        print(
            f"centroids: {centroids}\ndistance from centroid: {distance_from_centroid}\nindices that meet criteria: {indices_meet_criteria}\n"
        )
    out_mask = np.isin(labeled_components, indices_meet_criteria)
    return out_mask

#### TODO review and document ####
def find_and_process_outliers(
    label_to_process,
    raw_depth_map: np.ndarray,
    difference_map: np.ndarray,
    ret_surf_coords: np.ndarray,
    rpe_surf_coords: np.ndarray,
    gap_threshold: float,
    pixel_thickness_threshold: float,
    component_to_central_retina_threshold: float,
):
    """ """
    # find outlier values
    show_info("Finding Outlier Values\n")
    diff = (
        difference_map > gap_threshold
    ) * 9  # mismatch outliers indicating gaps in the segmentaion
    diff2 = (
        (raw_depth_map >= pixel_thickness_threshold) & ~(diff)
    ) * 4  # mismatch from overly thick measurments 112 is slightly greater than 500 um
    outlier_map = (diff + diff2).astype(bool)
    # print(f"diff shape: {diff.shape}, label shape: {label.shape}\n")

    # Process surface outliers
    # replace outlier values in retina surface points
    ret_surf_replaced, ret_outlier_free, outlier_filled_height_map = outlier_correction(
        ret_surf_coords, outlier_map=outlier_map
    )
    ret_outliers = mask_3D_points_with_2D_boolean_mask(
        ret_surf_coords, mask=outlier_map, axis=1, invert_mask=False
    )
    rpe_outlier_free = mask_3D_points_with_2D_boolean_mask(
        rpe_surf_coords, mask=outlier_map, axis=1, invert_mask=True
    )

    # generate centroid surface for retina
    retina_surf_centroids = get_points_centroid_along_axis(
        ret_outlier_free, rpe_outlier_free, target_axes=[1]
    )
    # generate 3D outlier labels intersections
    diff_3D = project_2d_mask(label_to_process, diff)
    diff2_3D = project_2d_mask(label_to_process, diff2)
    intersect = diff_3D.astype(bool) & label_to_process.astype(bool)
    # recover label components close to the center of the retinal surface

    # centroid surface required to recover connected components near retinal surface
    if retina_surf_centroids.size != 0:
        recovered_components = mask_components_within_theshold_of_points_distribution(
            intersect,
            point_distirbution=retina_surf_centroids,
            threshold=component_to_central_retina_threshold,
        )
    else:
        recovered_components = np.zeros_like(label_to_process,dtype=bool) # return empty boolean

    intersect2 = (diff2_3D.astype(bool) & label_to_process.astype(bool)) * 4
    clean = (
        label_to_process.astype(bool)
        & ~intersect.astype(bool)
        & ~intersect2.astype(bool)
    ) + recovered_components

    return (
        clean,
        intersect2,
        recovered_components,
        intersect,
        diff2_3D,
        diff_3D,
        retina_surf_centroids,
        rpe_outlier_free,
        ret_outliers,
        ret_surf_replaced,
        ret_outlier_free,
        outlier_filled_height_map,
        outlier_map,
        diff2,
        diff,
    )

def clean_labels(
    label_data: np.ndarray,
    imaging_range: float = 12.0,
    refractive_index: float = 1.33,
    gap_threshold: int = 8,
    thickness_threshold: float = 500.0,
    incedence_allowance: float = 1 / np.sin(np.pi / 4),
    component_to_pixel_thickness_ratio: float = (1 / 3),
    dust_threshold: float = 1e6,
    viewer="",
    visualization_processing_flag:bool=False,
    verbose:bool=False,
):
    """
    """
    import napari
    import cc3d
    if not isinstance(viewer,napari.Viewer):
        show_info("Not Using Napari viewer instance.")
        viewer_flag = False
    else:
        show_info("Using Napari viewer instance.")
        viewer_flag = True

    raw_depth_map, ret_surf_coords, rpe_surf_coords, thick_map, difference_map = (
            generate_maps(label_data)
        )

    conv_factor = (
        imaging_range / label_data.shape[1] * 1000 / refractive_index
    )  # mm/pixel * um/mm /refractive index = um/pixel

    pixel_thickness_threshold = (
        int(thickness_threshold / conv_factor) * incedence_allowance
    )
    component_to_pixel_thickness_ratio = 1 / 3  # 1/2 #1/6 #1/8 #1/4 #1/2
    component_to_central_retina_threshold = (
        pixel_thickness_threshold * component_to_pixel_thickness_ratio
    )

    if verbose:
        print(
            f"Thresholdss\ngap: {gap_threshold}\nthickness theshold: {thickness_threshold}\nincedence allowance = {incedence_allowance}\npixel thicknes theshold: {pixel_thickness_threshold}\ndust threshold: {dust_threshold}\n"
        )
        print(
            f"component to pixel thickness ratio: {component_to_pixel_thickness_ratio}\ncomponent to central retina threshold: {component_to_central_retina_threshold}\n"
        )

    (
        clean,
        intersect2,
        recovered_components,
        intersect,
        diff2_3D,
        diff_3D,
        retina_surf_centroids,
        rpe_outlier_free,
        ret_outliers,
        ret_surf_replaced,
        ret_outlier_free,
        outlier_filled_height_map,
        outlier_map,
        diff2,
        diff,
    ) = find_and_process_outliers(
        label_data,
        raw_depth_map,
        difference_map,
        ret_surf_coords,
        rpe_surf_coords,
        gap_threshold=gap_threshold,
        pixel_thickness_threshold=pixel_thickness_threshold,
        component_to_central_retina_threshold=component_to_central_retina_threshold,
    )

    # process small remnants
    show_info("Processing Small Components\n")
    dust_free = cc3d.dust(clean, threshold=dust_threshold).astype("bool") * 6
    outliers = (label_data.astype("bool") & ~dust_free.astype("bool")) * 10
    outliers_coord_mask = (
        outliers.sum(axis=1).astype(bool) * 1
        - recovered_components.sum(axis=1).astype(bool) * 1
    ).astype(bool)
    num_outliers = np.count_nonzero(outliers)
    num_labeled = np.count_nonzero(label_data)
    percent_outliers = (num_outliers / num_labeled) * 100
    show_info(
        f"{num_outliers}/{num_labeled} outliers {percent_outliers}%\n"
    )

    # TODO revisit this intersect would need to be recalculated to get an accurate reading with the recovered data
    # TODO verify that outlier_coord_mask is accurate and also recalculate. Then perform thickness calculations!!
    show_info("Processing Final Cleanup\n")
    (
        raw_depth_map2,
        ret_surf_coords2,
        rpe_surf_coords2,
        thick_map2,
        difference_map2,
    ) = generate_maps(dust_free.astype("bool") * 1)

    if visualization_processing_flag:
        (
            clean2,
            intersect2_2,
            recovered_components2,
            intersect_2,
            diff2_3D2,
            diff_3D2,
            retina_surf_centroids2,
            rpe_outlier_free2,
            ret_outliers2,
            ret_surf_replaced2,
            ret_outlier_free2,
            outlier_filled_height_map2,
            outlier_map2,
            diff2_2,
            diff_2,
        ) = find_and_process_outliers(
            dust_free,
            raw_depth_map2,
            difference_map2,
            ret_surf_coords2,
            rpe_surf_coords2,
            gap_threshold=gap_threshold,
            pixel_thickness_threshold=pixel_thickness_threshold,
            component_to_central_retina_threshold=component_to_central_retina_threshold,
        )

        recovered_components2 = mask_components_within_theshold_of_points_distribution(
            intersect_2,
            point_distirbution=retina_surf_centroids2,
            threshold=component_to_central_retina_threshold,
        )

        squeaky_clean = (clean2.astype(bool) + recovered_components2) * 36

        outliers2 = (dust_free.astype("bool") & ~squeaky_clean.astype("bool")) * 10
        num_outliers2 = np.count_nonzero(outliers2)
        num_labeled2 = np.count_nonzero(dust_free)
        percent_outliers2 = (num_outliers2 / num_labeled2) * 100
        show_info(
            f"{num_outliers2}/{num_labeled2} outliers {percent_outliers2}%\n"
        )

    if viewer_flag:
        viewer.add_image(label_data, visible=False)
        viewer.add_image(raw_depth_map, visible=False)
        viewer.add_image(thick_map, visible=False)
        viewer.add_image(difference_map, visible=False)
        viewer.add_points(
            ret_surf_coords,
            size=4,
            face_color="red",
            name="retinal_surface",
            visible=False,
        )
        viewer.add_points(
            rpe_surf_coords,
            size=4,
            face_color="blue",
            name="rpe_surface",
            visible=False,
        )
        # viewer.add_points(retina_surf_centroids,size=4,face_color="magenta",name="retina_surf_centroids",visible=True)
        viewer.add_labels(diff, name="diff", visible=False)
        viewer.add_labels(diff2, name="diff2", visible=False)
        viewer.add_points(
            ret_surf_replaced,
            size=4,
            face_color="green",
            border_color="yellow",
            name="ret_surf_replaced",
            visible=True,
        )
        viewer.add_points(
            ret_outliers, size=4, face_color="red", border_color="orange", visible=True
        )
        viewer.add_points(
            ret_outlier_free,
            size=4,
            face_color="green",
            border_color="blue",
            visible=True,
        )
        viewer.add_labels(diff_3D, visible=False)
        viewer.add_labels(diff2_3D, visible=False)
        viewer.add_labels(intersect, visible=False)
        viewer.add_labels(recovered_components, visible=True)
        viewer.add_labels(intersect2, visible=False)
        viewer.add_image(outlier_filled_height_map, visible=False)
        viewer.add_labels(clean, visible=False)
        viewer.add_labels(dust_free, visible=True)
        viewer.add_labels(outliers)
        viewer.add_image(outliers_coord_mask)
        viewer.add_image(raw_depth_map2, visible=False)
        viewer.add_image(thick_map2, visible=False)
        viewer.add_image(difference_map2, visible=False)
        viewer.add_points(
            ret_surf_coords2,
            size=4,
            face_color="yellow",
            name="retinal_surface2",
            visible=True,
        )
        viewer.add_points(
            rpe_surf_coords2,
            size=4,
            face_color="purple",
            name="rpe_surface2",
            visible=True,
        )

        if visualization_processing_flag:
            viewer.add_image(outlier_filled_height_map2, visible=False)
            viewer.add_labels(diff_3D2, visible=False)
            viewer.add_labels(diff2_3D2, visible=False)
            viewer.add_labels(outliers2)
            viewer.add_labels(recovered_components2, visible=True)
            viewer.add_labels(squeaky_clean)
            viewer.add_points(
                retina_surf_centroids2,
                size=4,
                face_color="magenta",
                name="retina_surf_centroids",
                visible=True,
            )
            viewer.add_points(
                ret_surf_replaced2,
                size=4,
                face_color="green",
                border_color="yellow",
                name="ret_surf_replaced",
                visible=True,
            )

    output = (
        raw_depth_map2,
        ret_surf_coords2,
        rpe_surf_coords2,
        thick_map2,
        difference_map2,
        outliers_coord_mask,
        dust_free,
        percent_outliers,
    )
    return output

# TODO improve documentation
# Intended to cleanup artifacts introduced after performing grid_sample during desine operation on label data
def find_indices_after(volume, val_a, val_b, axis,device):
    # Ensure inputs are tensors and correct types
    #volume = torch.as_tensor(volume, dtype=torch.long)
    volume = volume.to(torch.long)
    volume_ndim = volume.ndim
    val_a = int(val_a)
    val_b = int(val_b)
    axis = int(axis)

    shape = volume.shape
    axis_len = shape[axis]

    # Mask for occurrences of B
    b_mask = (volume == val_b)
    # Mask for occurrences of A
    a_mask = (volume == val_a)

    del volume
    gc.collect()
    torch.cuda.empty_cache()

    # Find the index of the last B along the axis.
    # Flip the mask along the axis, find the first True, convert back to original index
    reversed_b_mask = b_mask.flip(dims=[axis])
    # argmax returns the first index of maximum (True) along the dim
    first_idx_reversed = torch.argmax(reversed_b_mask.long(), dim=axis)

    del reversed_b_mask
    gc.collect()
    torch.cuda.empty_cache()

    # Create a mask for slices where B is actually present (argmax on all False gives 0)
    b_exists = torch.max(b_mask, dim=axis, keepdim=False)[0]

    del b_mask
    gc.collect()
    torch.cuda.empty_cache()

    # Calculate last B index in original tensor's frame.
    # If B is not present (b_exists is False), the index should not allow any 'after' indices.
    # Setting it to axis_len - 1 will ensure no 'after' indices.
    last_b_idx = (axis_len - 1) - first_idx_reversed
    last_b_idx[~b_exists] = axis_len - 1 # Use advanced indexing to correct values

    del b_exists
    gc.collect()
    torch.cuda.empty_cache()

    # Expand last_b_idx to the full volume shape for broadcasting the comparison
    # Create an index tensor along the axis
    #ax_indices = torch.arange(axis_len, device=volume.device)
    ax_indices = torch.arange(axis_len, device=device)
    # Reshape ax_indices to broadcast correctly against last_b_idx
    broadcast_shape = [1] * volume_ndim
    broadcast_shape[axis] = axis_len
    ax_indices = ax_indices.view(broadcast_shape)

    del broadcast_shape
    gc.collect()
    torch.cuda.empty_cache()

    # Create a mask for all elements AFTER the last B index
    # (index > last_b_idx)
    after_last_b_mask = (ax_indices > last_b_idx.unsqueeze(axis))

    del ax_indices, last_b_idx
    gc.collect()
    torch.cuda.empty_cache()

    # Combine the masks: A is present AND it's after the last B
    final_mask = a_mask & after_last_b_mask

    del a_mask, after_last_b_mask
    gc.collect()
    torch.cuda.empty_cache()

    # Return the indices of the final mask
    return torch.nonzero(final_mask).T.cpu().numpy()
